
theme: jekyll-theme-cayman
title: reflective-mockk
description: Stub mockks programmatically using kotlin-reflect.
version: 1.0.0
docsDir: https://episode6.github.io/reflective-mockk/docs/v1.0.0
kotlinVersion: 1.7.10
