name: Build and Check
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  build-and-check-job:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Decode keystore
      env:
        ENCODED_STRING: ${{ secrets.ANDROID_SIGNING_KEY }}
      run: |
        echo $ENCODED_STRING | base64 -d > keystore.jks

    - name: Assemble project
      run: ./gradlew assemble
      env:
        ORG_GRADLE_PROJECT_androidSigningKeyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

    - name: Cleanup keystore
      if: ${{ always() }}
      run: rm -f keystore.jks

    - name: Upload android app build output
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: android-app/build/outputs/
        retention-days: 7

    - name: Check project
      run: ./gradlew check
